/**
 * Model catalog seed — idempotent via ON CONFLICT DO UPDATE.
 *
 * TODO(operator): Review and update pricing before enabling cost accounting.
 * Prices below are approximate as of mid-2025 (USD per 1M tokens).
 * Provider pricing changes frequently — verify at each provider's pricing page.
 *
 * Providers map to providerNameSchema values: openai, anthropic, gemini,
 * openrouter, google-ai-studio. Gemini = BYOK Google AI.
 * google-ai-studio = hosted free-tier Google AI Studio access.
 */

import { config } from 'dotenv'
import { resolve } from 'node:path'

config({ path: resolve(import.meta.dirname, '../../../../apps/api/.env.local') })
config({ path: resolve(import.meta.dirname, '../../.env.local') })

import { createDb } from '../client.js'
import { ModelCatalogRepository } from '../repositories/model-catalog.repository.js'
import type { NewModelCatalogEntry } from '../schema/index.js'

const MODELS: NewModelCatalogEntry[] = [
  // ── OpenAI ──────────────────────────────────────────────────────────────────
  {
    provider: 'openai',
    modelId: 'gpt-4o',
    displayName: 'GPT-4o',
    description: 'High-intelligence multimodal flagship model',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputCostPer1m: '2.500000',
    outputCostPer1m: '10.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'medium',
    qualityTier: 'frontier',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'openai',
    modelId: 'gpt-4o-mini',
    displayName: 'GPT-4o mini',
    description: 'Affordable small model for lightweight tasks',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputCostPer1m: '0.150000',
    outputCostPer1m: '0.600000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'fast',
    qualityTier: 'economy',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'openai',
    modelId: 'o1',
    displayName: 'o1',
    description: 'Reasoning model for complex analytical tasks',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    inputCostPer1m: '15.000000',
    outputCostPer1m: '60.000000',
    // o1 does not support streaming in the standard sense and has limited tool use
    supportsStreaming: false,
    supportsVision: true,
    supportsTools: false,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'slow',
    qualityTier: 'frontier',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'openai',
    modelId: 'o1-mini',
    displayName: 'o1-mini',
    description: 'Faster, cheaper reasoning model',
    contextWindow: 128000,
    maxOutputTokens: 65536,
    inputCostPer1m: '3.000000',
    outputCostPer1m: '12.000000',
    supportsStreaming: false,
    supportsVision: false,
    supportsTools: false,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'medium',
    qualityTier: 'standard',
    isEnabled: true,
    isDeprecated: false,
  },

  // ── Anthropic ───────────────────────────────────────────────────────────────
  {
    provider: 'anthropic',
    modelId: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet',
    description: 'Highest level of intelligence and capability',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputCostPer1m: '3.000000',
    outputCostPer1m: '15.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'medium',
    qualityTier: 'frontier',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'anthropic',
    modelId: 'claude-3-5-haiku-20241022',
    displayName: 'Claude 3.5 Haiku',
    description: 'Fast and compact model for near-instant responsiveness',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputCostPer1m: '0.800000',
    outputCostPer1m: '4.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'fast',
    qualityTier: 'economy',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'anthropic',
    modelId: 'claude-3-opus-20240229',
    displayName: 'Claude 3 Opus',
    description: 'Powerful model for highly complex tasks (previous generation)',
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputCostPer1m: '15.000000',
    outputCostPer1m: '75.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'slow',
    qualityTier: 'frontier',
    isEnabled: true,
    isDeprecated: false,
  },

  // ── Gemini (BYOK via Google AI API) ─────────────────────────────────────────
  {
    provider: 'gemini',
    modelId: 'gemini-1.5-pro',
    displayName: 'Gemini 1.5 Pro',
    description: 'Mid-size multimodal model for complex reasoning',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    inputCostPer1m: '1.250000',
    outputCostPer1m: '5.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: true,
    speedTier: 'medium',
    qualityTier: 'frontier',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'gemini',
    modelId: 'gemini-1.5-flash',
    displayName: 'Gemini 1.5 Flash',
    description: 'Fast and versatile model for diverse tasks',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    inputCostPer1m: '0.075000',
    outputCostPer1m: '0.300000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: true,
    speedTier: 'fast',
    qualityTier: 'standard',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'gemini',
    modelId: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash',
    description: 'Next-gen fast model with improved performance',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    inputCostPer1m: '0.100000',
    outputCostPer1m: '0.400000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: true,
    speedTier: 'fast',
    qualityTier: 'standard',
    isEnabled: true,
    isDeprecated: false,
  },

  // ── Google AI Studio (hosted free-tier provider) ────────────────────────────
  {
    provider: 'google-ai-studio',
    modelId: 'gemini-1.5-pro',
    displayName: 'Gemini 1.5 Pro (Google AI Studio)',
    description: 'Hosted Google AI Studio Gemini Pro model for complex reasoning',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    inputCostPer1m: '1.250000',
    outputCostPer1m: '5.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: true,
    speedTier: 'medium',
    qualityTier: 'standard',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'google-ai-studio',
    modelId: 'gemini-1.5-flash',
    displayName: 'Gemini 1.5 Flash (Google AI Studio)',
    description: 'Hosted fast Google AI Studio Gemini model',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    inputCostPer1m: '0.075000',
    outputCostPer1m: '0.300000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: true,
    speedTier: 'fast',
    qualityTier: 'economy',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'google-ai-studio',
    modelId: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash (Google AI Studio)',
    description: 'Hosted fast Google AI Studio Gemini 2.0 model',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    inputCostPer1m: '0.100000',
    outputCostPer1m: '0.400000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: true,
    speedTier: 'fast',
    qualityTier: 'economy',
    isEnabled: true,
    isDeprecated: false,
  },

  // ── OpenRouter ──────────────────────────────────────────────────────────────
  {
    provider: 'openrouter',
    modelId: 'openai/gpt-4o',
    displayName: 'GPT-4o (via OpenRouter)',
    description: 'OpenAI GPT-4o routed through OpenRouter',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputCostPer1m: '2.500000',
    outputCostPer1m: '10.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'medium',
    qualityTier: 'frontier',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'openrouter',
    modelId: 'anthropic/claude-3.5-sonnet',
    displayName: 'Claude 3.5 Sonnet (via OpenRouter)',
    description: 'Anthropic Claude 3.5 Sonnet routed through OpenRouter',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputCostPer1m: '3.000000',
    outputCostPer1m: '15.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'medium',
    qualityTier: 'frontier',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'openrouter',
    modelId: 'google/gemini-pro-1.5',
    displayName: 'Gemini Pro 1.5 (via OpenRouter)',
    description: 'Google Gemini 1.5 Pro routed through OpenRouter',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    inputCostPer1m: '1.250000',
    outputCostPer1m: '5.000000',
    supportsStreaming: true,
    supportsVision: true,
    supportsTools: true,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'medium',
    qualityTier: 'frontier',
    isEnabled: true,
    isDeprecated: false,
  },
  {
    provider: 'openrouter',
    modelId: 'meta-llama/llama-3.1-70b-instruct',
    displayName: 'Llama 3.1 70B (via OpenRouter)',
    description: 'Meta Llama 3.1 70B open model routed through OpenRouter',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    inputCostPer1m: '0.900000',
    outputCostPer1m: '0.900000',
    supportsStreaming: true,
    supportsVision: false,
    supportsTools: false,
    supportsJson: true,
    supportsFiles: false,
    speedTier: 'medium',
    qualityTier: 'standard',
    isEnabled: true,
    isDeprecated: false,
  },
]

async function seed() {
  const databaseUrl = process.env['DATABASE_URL']
  if (!databaseUrl) {
    throw new Error('DATABASE_URL is required — set it in .env.local or apps/api/.env.local')
  }

  const db = createDb(databaseUrl)
  const repo = new ModelCatalogRepository(db)

  console.log(`Seeding ${MODELS.length} models...`)
  for (const model of MODELS) {
    await repo.upsert(model)
    console.log(`  ✓ ${model.provider}/${model.modelId}`)
  }
  console.log('Model catalog seed complete.')
  process.exit(0)
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
